---
    root: true
    env:
        es6: true
        browser: true
        webextensions: true
    parserOptions:
        ecmaVersion: "latest"
        sourceType: "module"
    extends:
        - "eslint:recommended"
    ignorePatterns:
        - "src/**/*.test.js"
